#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=../../lib/require.bash
source "$SCT_LIBDIR/require.bash"
# shellcheck source=../../lib/path.bash
source "$SCT_LIBDIR/path.bash"

# Helper that automatically locates the docker compose file
# All arguments are passed to docker compose
compose() {
	require docker

	local compose_file
	compose_file="$(find_compose_file)"

	exec docker compose -f "$compose_file" "$@"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
then
	compose "$@"
fi
