name: CLI Tests

on:
  push:
    branches: [master]
    paths:
      - 'cli/**'
      - '.github/workflows/cli-tests.yml'
  pull_request:
    paths:
      - 'cli/**'
      - '.github/workflows/cli-tests.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # bats is a submodule

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest  # Avoid buggy 2.24.x versions

      - name: Run tests
        run: |
          cd cli
          ./run-tests.bash
        env:
          LC_ALL: C
          TERM: xterm
          BATS_OPTS: -F pretty
